language: python
sudo: false
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "pypy"
install:
    - python bootstrap.py
    - bin/buildout
script:
    - bin/test -v1
notifications:
    email: false
cache:
  pip: true
  directories:
    - eggs/
